add specific tag to base image, should fix missing library issue
svalinn/parastell pull request #114
Opened 2024-06-21 13:32 UTC by Edgar-21

2024-06-23 20:08 UTC, gonuke requested changes
Can you saw more in the description about which library was missing and/or refer to an issue that documents this?  It's useful to know what problem a PR is actually solving.

2024-06-23 20:08 UTC, gonuke commented on Dockerfile
> -                        libgl1-mesa-dev \
original indentation is a little clearer as these are arguments to `apt-get`

2024-06-24 02:38 UTC, Edgar-21 commented
My apologies, I edited the description to provide some more detail. This was mentioned briefly in the parastell channel a few weeks back as well, just took me a while to get around to submitting this PR.

2024-06-24 11:26 UTC, gonuke commented
It looks like `libtiff5-dev` is available - can we try switching to that and unpinning the miniconda image version?  Pinning specific versions usually ends up leading to trouble down the road...

2024-06-24 14:36 UTC, gonuke approved these changes

2024-06-24 14:36 UTC, merged