Full model DAGMC faceting via CAD-to-DAGMC
svalinn/parastell pull request #180
Opened 2024-12-12 22:16 UTC by connoramoreno

This branch adds support for a fully open-source, freely available DAGMC faceting workflow via CAD-to-DAGMC. This workflow is implemented as an alternative to the Cubit DAGMC faceting workflow.

Changes included in this branch:

- Introduces a new `Stellarator.export_cad_to_dagmc` method to automate DAGMC model generation via CAD-to-DAGMC and adds it to test and example scripts
- Renames the `Stellarator.export_dagmc` method, which generates DAGMC models via Cubit, to `Stellarator.export_cf_dagmc` and updates syntax in test and example scripts
- Removes the `InVesselBuild.export_cad_to_dagmc` method as it is made redundant by the `Stellarator.export_cad_to_dagmc` method and removes it from test and example scripts
- Modifies the magnet modeling workflow to store CAD solids in the `MagnetSet.coil_solids` parameter for future reference

This PR is considered a draft since test runs on full ParaStell geometries are running out of memory on my local machine. That said, CAD-to-DAGMC is able to successfully mesh our simple test geometry.

2025-01-03 19:59 UTC, connoramoreno commented
It should be noted that the "Regular CI testing for parastell / Perform CI Tests" workflow is failing because it is not pulling the Docker image corresponding to this branch

2025-01-03 20:04 UTC, connoramoreno commented
@bquan0, do you know how to fix the issue mentioned in the above comment, concerning the proper image tag being used?

2025-01-03 20:59 UTC, bquan0 commented
It's because of [this line](https://github.com/svalinn/parastell/blob/12cf70afc7e80b0556feb21f32ef552995d47fc1/.github/workflows/ci.yml#L15). `container: ghcr.io/svalinn/parastell-ci` means it always pulls the `latest` image. 
It needs some logic similar to [this line in docker_publish.yml](https://github.com/svalinn/parastell/blob/12cf70afc7e80b0556feb21f32ef552995d47fc1/.github/workflows/docker_publish.yml#L62) where it determines if it needs the extra tag if it's not on the `main` branch.

2025-01-03 21:05 UTC, connoramoreno commented
I figured as much! Just unsure how to go about retrieving the proper tag. Would it be done similarly to [this line](https://github.com/svalinn/parastell/blob/12cf70afc7e80b0556feb21f32ef552995d47fc1/.github/workflows/docker_publish.yml#L43)?

2025-01-03 23:04 UTC, bquan0 commented
I think you would have to run an extra job before `test-dependency-img` that echoes the tag to an `output`, like in [line 46](https://github.com/svalinn/parastell/blob/12cf70afc7e80b0556feb21f32ef552995d47fc1/.github/workflows/docker_publish.yml#L46). This is because ENV variables can't be used in `container:`, I think.

2025-01-06 17:59 UTC, connoramoreno commented
Since "**Build & publish Docker image for ParaStell CI / Test CI Image**" runs our test suite when we've made changes to any file affecting our Docker image, I'm going to add a condition to "**Regular CI testing for parastell / Perform CI Tests**" that will prevent its execution (returning the "Success" status) should any of those aforementioned files be modified. In effect, this change will make it such that our CI testing will defer to "**Build & publish Docker image for ParaStell CI / Test CI Image**" to test the code under the condition that the Docker image has been modified.

2025-01-13 02:25 UTC, gonuke requested changes
Just a couple of little comments.  Are there any important limitations?

2025-01-13 02:25 UTC, gonuke commented on parastell/magnet_coils.py
> +        [mat_tags.append(self.mat_tag) for _ in self.coil_solids]
This seems more readable to me
```suggestion
        mat_tags.extend([self.mat_tag] * len(self.coil_solids))
```

2025-01-13 02:25 UTC, gonuke commented on parastell/parastell.py
> +export_cf_dagmc_allowed_kwargs = [
What does `cf` mean here?

2025-01-13 02:25 UTC, gonuke commented on parastell/parastell.py
> +export_cf_dagmc_allowed_kwargs = [
I think it's for Coreform?  I wonder if `cubit` would be better than `cf`?

2025-01-16 15:47 UTC, connoramoreno commented on parastell/parastell.py
> +export_cf_dagmc_allowed_kwargs = [
Yes, `cf` refers to Coreform. I was copying their DAGMC export syntax in older versions of Cubit, but I agree using `cubit` would be clearer in our case.

2025-01-23 17:42 UTC, gonuke requested changes
A couple of minor comments to finalize this.

Also do we have any examples using the new capability? I see the examples are all updated, but still only include Cubit cases - is that right?

2025-01-23 17:42 UTC, gonuke commented on parastell/parastell.py
>          self._logger.info("Exporting DAGMC neutronics model...")
```suggestion
        self._logger.info("Exporting DAGMC neutronics model using Coreform Cubit...")
```

2025-01-23 17:42 UTC, gonuke commented on parastell/parastell.py
> +        self._logger.info("Exporting DAGMC neutronics model...")
```suggestion
        self._logger.info("Exporting DAGMC neutronics model with CAD-to-DAGMC ...")
```

2025-01-23 17:42 UTC, gonuke commented on parastell/magnet_coils.py
> +    def extract_solids_and_mat_tag(self, solids, mat_tags):
In general, I find it a little unsettling to have functions that change the input parameters and pass them back as new output parameters.

I wonder if it's better to just return these solids and tags, and append/extend outside of the function? I guess that can be accomplished by passing in empty lists...??

If we are appending in this function, maybe the function name should be `append_solids_and_mat_tags` rather than `extract_solids_and_mat_tag`?

2025-01-23 20:26 UTC, connoramoreno commented
I'll add an example that uses CAD-to-DAGMC

2025-01-23 20:30 UTC, connoramoreno commented on parastell/magnet_coils.py
> +    def extract_solids_and_mat_tag(self, solids, mat_tags):
Fair point! I think I prefer the former. In the case that we append/extend outside the function, it shouldn't be necessary to provide any input arguments.

2025-01-27 13:50 UTC, gonuke requested changes

2025-01-27 13:50 UTC, gonuke commented on parastell/parastell.py
> +        solids = ivb_solids + ms_solids
This may fail if there is no IVB or no magnets.  Maybe another test case?

2025-01-27 16:09 UTC, gonuke approved these changes
This looks great @connoramoreno - thanks for this improvement

2025-01-27 16:10 UTC, merged