split MagnetSet and MagnetCoil
svalinn/parastell pull request #182
Opened 2024-12-27 19:10 UTC by Edgar-21

2025-01-16 16:52 UTC, connoramoreno requested changes
Here are some initial thoughts - we can discuss these further if you disagree. This branch will also need to be rebased onto `main`.

2025-01-16 16:52 UTC, connoramoreno commented on parastell/magnet_coils.py
>          (Internal function not intended to be called externally)
Would this not also be useful for imported geometries?

2025-01-21 14:31 UTC, Edgar-21 commented on parastell/magnet_coils.py
> +        coils_file (str): path to coil filament data file.
I agree, I'll tackle updating rdu to work with both subclasses in an upcoming PR, I've created an issue and assigned myself here #186

2025-01-21 14:33 UTC, Edgar-21 commented on parastell/magnet_coils.py
> +            data and [cm] (defaults to m2cm = 100).
yes, with removing the filament data from this subclass that makes sense

2025-01-21 14:34 UTC, Edgar-21 commented on parastell/magnet_coils.py
>          (Internal function not intended to be called externally)
I'm assuming that people who bring their own cad will have it in state where it matches their geometry, or will have the means to do that.

2025-01-21 14:58 UTC, Edgar-21 commented on parastell/magnet_coils.py
> +            is saved.
yeah seems like a good plan

2025-01-22 19:17 UTC, connoramoreno requested changes
Just a quick thing on Cubit syntax for newer versions. We can (potentially) submit an additional review after Friday's meeting.

2025-01-24 19:15 UTC, Edgar-21 commented on parastell/magnet_coils.py
> +    def sort_filaments_toroidally(self):
move this this to MagnetSetFromFilaments()

2025-01-24 22:56 UTC, connoramoreno commented
@gonuke, Edgar and I discussed the software design of the code changes in `magnet_coils.py` and we'd like your input on best practices/pythonicity. I'm mostly on board with the changes Edgar is introducing here but I'm hesitant to approve this PR with the current implementation of the parent class `MagnetSet`. Specifically, `MagnetSet` is not functional as a stand-alone class. Although it's a parent class, it relies on member variables, including `self.geometry_file` and `self.working_dir` in the `import_geom_cubit` method, being set by one of the child classes. Is that okay? I'm unsure what "proper" protocol is here.

2025-01-24 23:15 UTC, gonuke commented
> @gonuke, Edgar and I discussed the software design of the code changes in `magnet_coils.py` and we'd like your input on best practices/pythonicity. I'm mostly on board with the changes Edgar is introducing here but I'm hesitant to approve this PR with the current implementation of the parent class, `MagnetSet`. Specifically, `MagnetSet` is not functional as a stand-alone class. Although it's a parent class, it relies on member variables, including `self.geometry_file` and `self.working_dir` in the `import_geom_cubit` method, being set by one of the child classes. Is that okay? I'm unsure what "proper" code design is here.

In general, this is a common pattern.  For example, in C++, it's common to have a parent class that defines a common API (i.e. a set of functions) but define those function in the parent class to be explicitly undefined so that it's never legal to define an object from that parent class.

I'll take a closer look at this specific implementation to see if I have any thoughts, though.

2025-01-27 18:11 UTC, Edgar-21 commented on parastell/cubit_io.py
> +    cubit.cmd(f'export cf_dagmc "{export_path}" overwrite')
I suppose I can upgrade, this has now been reverted

2025-01-27 20:47 UTC, connoramoreno reviewed
This is looking pretty good to me now, thanks @Edgar-21. I'll hold off on approving/merging until Paul gives his thoughts on our software design discussion

2025-01-27 20:47 UTC, connoramoreno commented on tests/test_magnet_coils.py
> +
Nice

2025-01-27 20:49 UTC, connoramoreno commented on tests/test_magnet_coils.py
> +
I'd like to change all of the tests to use this routine. I think a separate PR would be most appropriate for that though.

2025-01-28 14:57 UTC, gonuke requested changes
I think the code looks OK.  It's a little hard to track all the changes because many of them are just a reorganization of existing code that are hard to compare because of how they have moved in the file.  It seems OK to me.

I have one minor request on the organization of the

2025-01-28 14:57 UTC, gonuke commented on .gitignore
> +!magnet_geom.step
And maybe a comment for any of the exceptinos...

2025-01-29 23:11 UTC, Edgar-21 commented on .gitignore
> +!magnet_geom.step
grouped the test files together

2025-01-29 23:21 UTC, Edgar-21 commented
rebased, and made a few changes to get things working with the new cad to dagmc methods. I've added a method to InvesselBuild() and MagnetSet() that adds the geometry to a cad_to_dagmc instance, rather than getting the cad solids from each class and combining them in Stellarator.build_cad_to_dagmc_model()

2025-01-31 18:21 UTC, connoramoreno requested changes
A comment about code structure, almost done!

2025-01-31 18:21 UTC, connoramoreno commented on parastell/parastell.py
> +            self.magnet_set.add_solids_to_cad_to_dagmc(self.dagmc_model)
Let's modify this structure to make it more transparent what's happening in these methods (per our discussion in Hacker Within).

2025-01-31 21:12 UTC, Edgar-21 commented on parastell/parastell.py
> +            self.magnet_set.add_solids_to_cad_to_dagmc(self.dagmc_model)
donezo

2025-01-31 21:41 UTC, connoramoreno approved these changes
Looks great! Thanks for this upgrade @Edgar-21

2025-01-31 21:42 UTC, connoramoreno commented
Just need @gonuke to approve before we can merge.

2025-01-31 22:20 UTC, gonuke approved these changes
Thanks @Edgar-21

2025-01-31 22:42 UTC, merged