YAML reader function
svalinn/parastell pull request #70
Opened 2024-03-30 02:15 UTC by connoramoreno

Changes the location of the YAML reader function `read_yaml_config`. Previously, each ParaStell script had an identical `read_yaml_config` function to read YAML input. This PR moves this function to `utils.py`, and each script then imports it.

Closes #54

2024-03-30 02:20 UTC, connoramoreno commented
It should be noted that this is a draft since the relative imports in each script seem to be causing issues when using YAML input from the command line. For example, assuming parastell.py and config.yaml are in the same directory, the command
```
python3 parastell.py config.yaml
```
results in the following error:
```
Traceback (most recent call last):
  File "/home/camoreno/parastell/parastell/parastell.py", line 6, in <module>
    from . import log
ImportError: attempted relative import with no known parent package
```

2024-03-31 21:45 UTC, gonuke commented
I think we'll want to get to a point where we actually install this rather than just run from the source directory.  Alternatively, we put the `parastell` directory in the python path?

2024-04-01 16:40 UTC, connoramoreno commented
This is with `parastell` on `PYTHONPATH`, specifically the repository directory. This also uses the updated file structure.

2024-04-01 16:45 UTC, connoramoreno commented
Executing from a different directory with `config.yaml`,
```
python3 ~/parastell/parastell/parastell.py config.yaml
```
results in the same error.

2024-04-02 17:21 UTC, gonuke commented
If that fixes it, I guess let's change it. Separately, I'd like to better understand these relative imports, because they should work.

2024-04-02 18:27 UTC, connoramoreno commented
They work when ParaStell is imported as a module, but not when run directly with a YAML input.

2024-04-02 18:29 UTC, connoramoreno commented
It might be that relative imports are defined only for Python modules, but when these scripts are run from command line with a YAML argument, they might not be considered modules by Python anymore

2024-04-03 01:08 UTC, gonuke commented
Yes... so I think the right way to do this is to generate a lightweight script that imports `parastell` and calls `parastell.parastell()`

if you make a file called `stellarator` with these contents and `chmod u+x`, it works.
```
#!/usr/bin/env python3

from parastell import parastell

parastell.parastell()
```

and make it executable.

I think there are simple ways to do this with setup tools as part of installation. But that may be for another time.

2024-04-17 14:38 UTC, connoramoreno commented
I am planning to lump in the solution we discussed for #52 into this PR since it's so related, unless there are any objections.

2024-04-17 14:40 UTC, connoramoreno commented
Also considering rebasing this onto `null-logger` since there are some changes in that branch that affect the YAML input workflow.

2024-04-20 16:21 UTC, gonuke requested changes
Just a minor comment on naming the executables.

2024-04-20 16:21 UTC, gonuke commented on executables/invessel_build.py
Maybe name these without the `.py` extension?

2024-04-20 16:21 UTC, gonuke commented on executables/invessel_build.py
Also, if we figure out how to use `pip install` correctly, these can be automatically generated in the right place in the path.

2024-04-22 16:19 UTC, connoramoreno commented on executables/invessel_build.py
Would we rather make ParaStell pip-installable or condo-installable, given the dependency on conda packages? I'm not sure that some of our dependencies can be installed via pip.

2024-04-25 11:31 UTC, gonuke commented on executables/invessel_build.py
`pip` can also be used to install the software from the source code in a local place on the Python path.   This is the mode I'm thinking of, not necessarily installing with `pip` from PyPi

2024-04-25 11:31 UTC, gonuke approved these changes
LGTM - thanks @connoramoreno

2024-04-25 11:32 UTC, merged